import Footer from "../components/footer/footer";
import Navbar from "../components/navbar/navbar";
import Head from 'next/head';
import Style from '../styles/Layout.module.css';
const Layout = ({ children }) => {
  return (
    <>
      <div className={Style.layout}>
        <Head>
          <title>First App</title>
          <meta name="descriptiondescription" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <main>
        {children}
        </main>

        <Footer />
      </div>
    </>
  );
};

export default Layout;
