import Footer from "../components/footer";
import Navbar from "../components/navbar";
import Head from 'next/head';
import Style from './Layout.module.css';
const Layout = ({ children }) => {
  return (
    <>
      <div className={Style.layout}>
        <Head>
          <title>First App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        {children}
        <Footer />
      </div>
    </>
  );
};

export default Layout;
